___

<a href='https://mainacademy.ua/'> <img src='https://mainacademy.ua/wp-content/uploads/2019/03/logo-main.png' alt = 'Хмм, щось з інтернетом'/></a>
___

# Module 5: Data analysis with NumPy and Pandas

## Lab work 5.1



#### Мета: 

* навчитися працювати із бібліотекою NumPy в Python

### Завдання:

In [1]:
import numpy as np

Вивести версію та конфігурацію бібліотеки:

In [2]:
print (np.__version__)

1.20.1


Створити вектор з 10 елементів, заповнений одиницями:

In [4]:
a = np.ones(10)
print(a)

[1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]


Створити вектор із значеннями від 0 до 10:

In [5]:
a = np.arange(0,11)
print(a)

[ 0  1  2  3  4  5  6  7  8  9 10]


Створити матрицю 5 на 5, заповнену нулями:

In [6]:
np.full((5, 5), 0)

array([[0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0]])

Заповнити вектор з 20 елементів випадковими цілими числами. Знайти індекси ненульових елементів:

In [7]:
a = np.random.randint(0, 20 + 1, 20)
nz = np.nonzero(a)
print(nz)

(array([ 0,  1,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 14, 15, 16, 17, 18,
       19], dtype=int64),)


Для вектора із попередньої задачі знайти середнє значення, медіану, стандартне відхилення:

In [8]:
m = np.mean(nz)
md = np.median(nz)
s = np.std(nz)
print(m, md, s)

9.722222222222221 9.5 5.752347883502831


Створити дві матриці випадкових чисел розміром 4х2 та 2х2. Перемножити їх:

In [9]:
a = np.random.random((4,2))
b = np.random.random((2,2))
c = np.dot(a, b)
print(c)

[[0.53456405 0.93566894]
 [0.57708746 1.49826824]
 [0.42992348 1.03635632]
 [0.29175731 1.19406691]]


Результуючу матрицю із попередньої задачі перетворити у вектор. Знайти мінімальне та максимальне значення. 

Максимальне значення замінити на 0:

In [10]:
v = np.ravel(c)
print(v)
v_max = np.max(v)
v_min = np.min(v)
print(v_max, v_min)
v_max = 0
print(v_max, v_min)

[0.53456405 0.93566894 0.57708746 1.49826824 0.42992348 1.03635632
 0.29175731 1.19406691]
1.4982682410242605 0.29175730865926486
0 0.29175730865926486


Знайдіть кореляцію першого рядка матриці із попереднього завдання із іншими рядками:

In [14]:
m = c[0, :]
n1 = c[1, :]
n2 = c[2, :]
n3 = c[3, :]
k1 = np.corrcoef(m, n1)
k2 = np.corrcoef(m, n2)
k3 = np.corrcoef(m, n3)
print(k1, k2, k3)

[[1. 1.]
 [1. 1.]] [[1. 1.]
 [1. 1.]] [[1. 1.]
 [1. 1.]]


In [ ]:
m = c[0, :]
n = c[1:4, :]
k = np.corrcoef(m, n)
print(k)

Дано матрицю. Знайти ранг матриці:

In [11]:
a = np.array([[ 1,  4, 5],
              [7, 3, 2],
              [9, 16, 1]])
np.linalg.matrix_rank(a)

3

Знайти визначник матриці:

In [12]:
np.linalg.det(a)

440.0000000000002

Знайти власні значення та власні вектори матриці: 

In [13]:
np.linalg.eigh(a)

(array([-14.30540864,  -4.34740072,  23.65280936]),
 array([[ 0.15315575,  0.88160309,  0.44645191],
        [ 0.63674998, -0.43353159,  0.6376518 ],
        [-0.75570681, -0.18661821,  0.62775861]]))

Знайдіть число, що найчастіше зустрічається в масиві:

In [15]:

a = np.random.randint(0,10,50)
cs = np.bincount(a)
print(np.argmax(cs))

1


In [16]:
import collections
collections.Counter(a.flatten())

Counter({2: 3, 1: 9, 3: 4, 0: 8, 8: 5, 6: 6, 9: 2, 4: 9, 7: 2, 5: 2})

Виведіть лише парні числа, що діляться на 5:

In [24]:
a = np.random.randint(0,51,100)
for i in a:
    if i == 0:
        pass
    elif i % 2 == 0 and i % 5 == 0:
        print(i)

30
10
50
20
50
10
50
10
20
20
10
50
50


Розв'яжіть систему рівнянь:
$$2x + 5y = 1 $$

$$x - 10y = 3  $$
   

In [25]:
a = [[2, 5], [1, -10]]
b = [1, 3]
x = np.linalg.solve(a, b)
print(x)

[ 1.  -0.2]


In [26]:
np.dot(a, x)

array([1., 3.])